#!/usr/bin/env bash

set -e

# Remove any previously compiled versions.
rm *.vsix || true

# Bump the version to ensure that it gets upgraded.
npm version patch --force

npm run esbuild
npm run compile

vsce package

# Install the compiled extension.
code --install-extension *.vsix