#!/usr/bin/env bash

source $HOME/bin/fix-paths.bash
set -e

rm *.vsix || true

# Bump the version to ensure that it gets upgraded.
npm version patch --force

npm run esbuild
npm run compile

vsce package
echo code --install-extension *.vsix
code --install-extension *.vsix